= Сервис работы с задачами

Настоящий документ содержит техническое описание HTTP-сервиса работы с задачами, структура данных которых приведена на xref:db/db.adoc[странице].

anchor:bookmark-c[]Сервис позволяет:

. Создавать задачи (xref:post/post.adoc[POST]).
. Получать список созданных задач (GET).
. Получать конкретную задачу из списка (GET).
. Изменять параметры задачи (PUT).
. Удалять задачу (DELETE). 

include::ver.adoc[]
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
kkkkkkkkkkkkkkkkkkkkkk
Описани <<bookmark-c>>